/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "psommqfuacsoeqvwzarp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzb21tcWZ1YWNzb2Vxdnd6YXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MTg0MzEsImV4cCI6MjA3NzA5NDQzMX0.I2U8A2YC7-LvzPJx9kxcEsBg-22CAGtAhMTERmobJdA"